apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: website-operator
  template:
    metadata:
      labels:
        name: website-operator
    spec:
      containers:
        - name: website-operator
          image: docker.io/surajnarwade/website-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - website-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "website-operator"
